secret:
  api:
    DATABASE_URL: "postgresql://neondb_owner:npg_wSgt7jmNKz1G@ep-patient-lake-afjzdcge.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
    JWT_ACCESS_SECRET: "c50c3f38-0757-4733-b83c-5c06d3457ab0"
    JWT_REFRESH_SECRET: "94d40690-cc0e-470d-ad45-c8b91e9914f3"