replicaCount: 2

# On ne fixe plus le namespace ici.
# L'idée est de pouvoir déployer le chart dans n'importe quel namespace
# sans modifier values.yaml ni les templates.
# Dans les manifests Helm, on utilise donc :
# namespace: {{ .Release.Namespace }}
#
# Exemple :
# helm install devops-api ./helm/devops-api -n devops-helm
#
# namespace: devops-demo

image:
  repository: ghcr.io/samuel-elie/devops-api

  # Évite "latest" en production :
  # - meilleur suivi des versions
  # - rollback plus propre
  # - Trivy/Kubernetes aiment mieux une version explicite
  #
  # Remplace par ton vrai tag CI/CD quand possible :
  # tag: "1.0.0"
  tag: "1.0.0"

  # IfNotPresent est souvent plus propre avec un tag versionné.
  # Si tu veux absolument forcer le pull à chaque fois, remets Always.
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  className: public
  host: api.devops.local
  path: /
  pathType: Prefix
  clusterIssuer: selfsigned-issuer

config:
  NODE_ENV: production

  # Mongo :
  # L'API parle au service headless/statefulset "mongo"
  MONGO_HOST: mongo
  MONGO_PORT: "27017"
  MONGO_DB: devopsdb

  # IMPORTANT :
  # avec MONGO_INITDB_ROOT_USERNAME / PASSWORD, l'utilisateur root
  # est créé dans la base "admin", donc l'authSource doit être "admin".
  #
  # Ancien test :
  # MONGO_AUTH_SOURCE: devopsdb
  MONGO_AUTH_SOURCE: admin

  # Redis :
  REDIS_HOST: redis-svc
  REDIS_PORT: "6379"

secret:
  MONGO_USER: devopsuser
  MONGO_PASSWORD: devopspass
  JWT_SECRET: change_me_very_long_secret

mongo:
  enabled: true
  image: mongo:6
  port: 27017
  storage: 5Gi

  # Ressources Mongo :
  # On les ajoute pour réduire les findings Trivy
  # et mieux cadrer la consommation.
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

redis:
  enabled: true
  image: redis:7-alpine
  port: 6379

  # Ressources Redis :
  resources:
    requests:
      cpu: "50m"
      memory: "64Mi"
    limits:
      cpu: "250m"
      memory: "256Mi"

networkPolicy:
  enabled: true

# Ressources de l'API
resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"