apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: taskflow-api
  namespace: observability
  labels:
    release: kube-prom-stack
spec:
  namespaceSelector:
    matchNames:
      - taskflow-dev
  selector:
    matchLabels:
      app: taskflow-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s