apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: taskflow-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: {{ .Values.replicaCount.api }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-api
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-api
        app.kubernetes.io/name: taskflow-api
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: Helm
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault

      volumes:
        - name: uploads
          emptyDir: {}

      containers:
        - name: api
          image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
          imagePullPolicy: {{ .Values.image.api.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.api.port }}

          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          volumeMounts:
            - name: uploads
              mountPath: /app/uploads

          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}-api-config
            - secretRef:
                name: {{ .Release.Name }}-api-secret

          readinessProbe:
            tcpSocket:
              port: {{ .Values.service.api.port }}
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            tcpSocket:
              port: {{ .Values.service.api.port }}
            initialDelaySeconds: 25
            periodSeconds: 10

          resources:
{{ toYaml .Values.resources.api | indent 12 }}