{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DATABASE_URL: {{ .Values.secret.api.DATABASE_URL | quote }}
  JWT_ACCESS_SECRET: {{ .Values.secret.api.JWT_ACCESS_SECRET | quote }}
  JWT_REFRESH_SECRET: {{ .Values.secret.api.JWT_REFRESH_SECRET | quote }}
{{- end }}