apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  # namespace: {{ .Values.namespace }}
  namespace: {{ .Release.Namespace }}
data:
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  PORT: {{ .Values.service.port | quote }}
  MONGO_HOST: {{ .Values.config.MONGO_HOST | quote }}
  MONGO_PORT: {{ .Values.config.MONGO_PORT | quote }}
  MONGO_DB: {{ .Values.config.MONGO_DB | quote }}
  MONGO_AUTH_SOURCE: {{ .Values.config.MONGO_AUTH_SOURCE | quote }}
  REDIS_HOST: {{ .Values.config.REDIS_HOST | quote }}
  REDIS_PORT: {{ .Values.config.REDIS_PORT | quote }}