{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redis-svc
  # namespace: {{ .Values.namespace }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: redis
spec:
  selector:
    app: redis
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
      protocol: TCP
{{- end }}