apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  # namespace: {{ .Values.namespace }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  MONGO_USER: {{ .Values.secret.MONGO_USER | quote }}
  MONGO_PASSWORD: {{ .Values.secret.MONGO_PASSWORD | quote }}
  JWT_SECRET: {{ .Values.secret.JWT_SECRET | quote }}